//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public int accountNo { get; set; }
        public string accountName { get; set; }
        public string accountPass { get; set; }
        public string accountType { get; set; }
    }
}
