//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }
        public System.DateTime workDate { get; set; }
        public string telephone { get; set; }
        public byte[] photo { get; set; }
    }
}
