//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public string CustomerName { get; set; }
        public string TransactionID { get; set; }
        public string CustomerChineseID { get; set; }
        public string RepaymentWeek { get; set; }
        public string CreditPurpose { get; set; }
        public string ApplicationDate { get; set; }
    }
}
